Add take drop
wunderdogsw/proem pull request #26
Opened 2019-03-01 06:34 UTC by villhei

Adding, take, drop, takeWhile and dropWhile.

take/drop are basically aliases for `Array.prototype.slice`, which nobody (tm) remembers what it does anyway.

2019-03-01 06:51 UTC, katis requested changes

2019-03-01 06:51 UTC, katis commented on packages/array/src/index.ts
> +export function take<A>(array: A[], n: number): A[] {
Olis kiva jos nämä olis toteutettu itse, niin voisi ottaa parametrina `ArrayLike<A>` ja sitten koodi toimisi argumentseille, DOM listoille yms. Palautustyyppinä voisi kuitenkin olla `A[]`.

2019-03-01 07:00 UTC, villhei commented on packages/array/src/index.ts
> +export function take<A>(array: A[], n: number): A[] {
Ok, enpä huomioinut tuota!

2019-03-02 08:09 UTC, katis requested changes

2019-03-02 08:09 UTC, katis commented on packages/array/src/index.ts
>  export function drop<A>(array: A[], n: number): A[] {
`ArrayLike<A>` parametrien tyypeiksi

2019-03-09 16:28 UTC, katis approved these changes

2019-03-09 16:28 UTC, merged